### ISSUE TITLE
[LOC] "__設定 _gt システム _gt フォーカスを支援__" needs to be replaced with "設定 > システム > 集中モード"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#129]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dc12e690-19c5-ba46-530f-56b2e4f2bb33
* Version Independent ID: 237aec15-eb8f-78ed-086f-518b4ce554dd
* Content: [新機能、Windows 10 Insider Preview ビルド (RS5)](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809)
* Content Source: [wip/at-home/Whats-new-wip-at-home-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-1809.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hyoshioka0128 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
Fixed.
Close #129

**Comment by hyoshioka0128** [comment]
Hi, @mypil .Reopen.
 #129 is not Fixed.

ja-jp:https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809
![whats-new-wip-at-home-1809_j5](https://user-images.githubusercontent.com/40815708/61993018-cce00480-b0a0-11e9-87e3-310b5abb0536.png)

en-us:https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1809
![whats-new-wip-at-home-1809_e5](https://user-images.githubusercontent.com/40815708/61993033-d9fcf380-b0a0-11e9-8705-231c757affa1.png)

**Comment by mypil** [comment]
@MollyMalone - Issue is not fixed yet. Can you please assist with this issue?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by mypil** [comment]
@hyoshioka0128 - Kindly check and validate if issue has been resolved. Thank you.

**Comment by hyoshioka0128** [comment]
@TinaMcN @mypil - Corrected.
Closed #129.
Thanks.
